# Generated by Django 5.1.1 on 2024-10-29 20:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Especialidad')),
                ('especialidad_nombre', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ['especialidad_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('estudio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estudio')),
                ('estudio_nombre', models.CharField(max_length=50, verbose_name='Nombre Estudio')),
                ('estudio_descripcion', models.CharField(max_length=100, verbose_name='Descripción Estudio')),
                ('estudio_precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Estudio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Estudios',
                'ordering': ['estudio_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Insumo')),
                ('insumo_nombre', models.CharField(max_length=50, verbose_name='Nombre Insumo')),
                ('insumo_descripcion', models.CharField(max_length=100, verbose_name='Descripción Insumo')),
                ('stock_actual', models.IntegerField(verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(verbose_name='Stock Mínimo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Insumos',
                'ordering': ['insumo_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Paciente')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('plan_seguro', models.CharField(max_length=50, verbose_name='Plan')),
                ('numero_asociado', models.CharField(max_length=20, unique=True, verbose_name='Número de Afiliado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='ProveedoresSeguros',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Proveedor')),
                ('proveedor_nombre', models.CharField(max_length=50, verbose_name='Nombre Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores de Seguros',
                'ordering': ['proveedor_nombre'],
            },
        ),
        migrations.CreateModel(
            name='IngresoVisita',
            fields=[
                ('visita_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Visita')),
                ('visita_fecha', models.DateField(verbose_name='Fecha Visita')),
                ('visita_hora', models.TimeField(verbose_name='Hora Visita')),
                ('visita_tipo', models.CharField(choices=[('SIN_TURNO', 'Ingreso por Guardia'), ('CON_TURNO', 'Ingreso con Turno')], default='SIN_TURNO', max_length=20)),
                ('visita_gravedad', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10, null=True)),
                ('estado', models.CharField(choices=[('Esperando', 'Esperando'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], max_length=20)),
                ('fecha_hora_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
            ],
            options={
                'verbose_name_plural': 'Visitas',
                'ordering': ['visita_fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('pago_creacion', models.DateField(verbose_name='Fecha Creación')),
                ('pago_fecha', models.DateField(verbose_name='Fecha Pago')),
                ('pago_monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'ordering': ['pago_fecha'],
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Factura')),
                ('factura_numero', models.IntegerField(unique=True, verbose_name='Número Factura')),
                ('factura_fecha', models.DateField(verbose_name='Fecha Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.pagos', verbose_name='ID Pago')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
                'ordering': ['factura_numero'],
            },
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('profesional_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Profesional')),
                ('profesional_nombre', models.CharField(max_length=50, verbose_name='Nombre Profesional')),
                ('profesional_apellido', models.CharField(max_length=50, verbose_name='Apellido Profesional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.especialidades')),
            ],
            options={
                'verbose_name_plural': 'Profesionales',
                'ordering': ['profesional_apellido'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='proveedor_nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.proveedoresseguros'),
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resultado')),
                ('resultado_detalle', models.CharField(max_length=200, verbose_name='Detalle Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resultado_fecha', models.DateField(verbose_name='Fecha Resultado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.estudios')),
                ('visita_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.ingresovisita')),
            ],
            options={
                'verbose_name_plural': 'Resultados de Laboratorio',
                'ordering': ['resultado_fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudesInsumos',
            fields=[
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Solicitud')),
                ('solicitud_fecha', models.DateField(verbose_name='Fecha Solicitud')),
                ('cantidad_solicitada', models.CharField(max_length=5, verbose_name='Cantidad Solicitada')),
                ('solicitado_por', models.CharField(max_length=50, verbose_name='Solicitado por')),
                ('fecha_completada', models.DateField(verbose_name='Fecha Completada')),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha Actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.insumos')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Insumos',
                'ordering': ['solicitud_fecha', 'estado_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programada'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.especialidades')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.estudios')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.paciente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='coreadmin.profesionales')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('professional', 'date', 'time')},
            },
        ),
        migrations.AddField(
            model_name='pagos',
            name='turno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.turnos'),
        ),
    ]
