# Generated by Django 5.1.1 on 2024-10-21 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Especialidad')),
                ('especialidad_nombre', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('estudio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estudio')),
                ('estido_nombre', models.CharField(max_length=50, verbose_name='Nombre Estudio')),
                ('estudio_descripcion', models.CharField(max_length=100, verbose_name='Descripción Estudio')),
                ('estudio_precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Estudio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Insumo')),
                ('insumo_nombre', models.CharField(max_length=50, verbose_name='Nombre Insumo')),
                ('insumo_descripcion', models.CharField(max_length=100, verbose_name='Descripción Insumo')),
                ('stock_actual', models.CharField(max_length=5, verbose_name='Stock Actual')),
                ('stock_minimo', models.CharField(max_length=5, verbose_name='Stock Mínimo')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Paciente')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedoresSeguros',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Proveedor')),
                ('proveedor_nombre', models.CharField(max_length=50, verbose_name='Nombre Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('pago_creacion', models.DateField(verbose_name='Fecha Creación')),
                ('pago_fecha', models.DateField(verbose_name='Fecha Pago')),
                ('pago_monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Factura')),
                ('factura_numero', models.IntegerField(unique=True, verbose_name='Número Factura')),
                ('factura_fecha', models.DateField(verbose_name='Fecha Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.pagos', verbose_name='ID Pago')),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('profesional_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Profesional')),
                ('profesional_nombre', models.CharField(max_length=50, verbose_name='Nombre Profesional')),
                ('profesional_apellido', models.CharField(max_length=50, verbose_name='Apellido Profesional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especialidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='SegurosPacientes',
            fields=[
                ('seguro_paciente_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Seguro')),
                ('seguro_nombre', models.CharField(max_length=50, verbose_name='Plan de Seguro')),
                ('numero_asociado', models.IntegerField(unique=True, verbose_name='Número de Afiliado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.proveedoresseguros')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudesInsumos',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Solicitud')),
                ('solicitud_fecha', models.DateField(verbose_name='Fecha Solicitud')),
                ('cantidad_solicitada', models.CharField(max_length=5, verbose_name='Cantidad Solicitada')),
                ('solicitado_por', models.CharField(max_length=50, verbose_name='Solicitado por')),
                ('fecha_completada', models.DateField(verbose_name='Fecha Completada')),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha Actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insumo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('turno_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Turno')),
                ('turno_fecha', models.DateField(verbose_name='Fecha Turno')),
                ('turno_hora', models.TimeField(verbose_name='Hora Turno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.paciente')),
                ('profesional_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.profesionales')),
            ],
        ),
        migrations.AddField(
            model_name='pagos',
            name='turno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreadmin.turnos'),
        ),
    ]
