# Generated by Django 5.1.1 on 2024-10-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='estudios',
            options={'verbose_name_plural': 'Estudios'},
        ),
        migrations.AlterModelOptions(
            name='facturas',
            options={'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='insumos',
            options={'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='profesionales',
            options={'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='proveedoresseguros',
            options={'verbose_name_plural': 'Proveedores de Seguros'},
        ),
        migrations.AlterModelOptions(
            name='resultadolaboratorio',
            options={'verbose_name_plural': 'Resultados de Laboratorio'},
        ),
        migrations.AlterModelOptions(
            name='segurospacientes',
            options={'verbose_name_plural': 'Seguros de Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesinsumos',
            options={'verbose_name_plural': 'Solicitudes de Insumos'},
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterModelOptions(
            name='visitasguardia',
            options={'verbose_name_plural': 'Visitas de Guardia'},
        ),
        migrations.AlterModelOptions(
            name='visitaslaboratorio',
            options={'verbose_name_plural': 'Visitas de Laboratorio'},
        ),
        migrations.RenameField(
            model_name='estudios',
            old_name='estido_nombre',
            new_name='estudio_nombre',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='segurospacientes',
            name='numero_asociado',
            field=models.CharField(max_length=15, unique=True, verbose_name='Número de Afiliado'),
        ),
    ]
