# Generated by Django 5.1.1 on 2024-10-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_asociado',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Afiliado'),
        ),
    ]
