# Generated by Django 5.1.1 on 2024-10-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudesinsumos',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='solicitudesinsumos',
            name='fecha_completada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Completada'),
        ),
    ]
