# Generated by Django 5.1.1 on 2024-10-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreadmin', '0002_alter_solicitudesinsumos_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnos',
            options={'ordering': ['date', 'time'], 'verbose_name_plural': 'Turnos'},
        ),
    ]
